### ISSUE TITLE
PR a odoo para que se creen impuestos con valor 0

### ISSUE THREAD

**Issue by jjscarafia** [odoo-argentina/account#5]
odoo ahora no crea impuestos si el valor del impuesto da 0, nos caga con "exento" "taza 0" y "no gravado". Entonces en [este archivo](https://github.com/odoo-argentina/account/blob/9.0/l10n_ar_account/models/account_tax.py) , modificamos la funcion directamente porque no era heredable. Lo ideal sea hacer un PR a odoo

**Comment by csrocha** [comment]
Fixed in https://github.com/odoo/odoo/commit/598856e1e0e4ca2d22aa1668212d14f242d530d0
